### ISSUE TITLE
【建议】修改文案

### ISSUE THREAD

**Issue by declandragon** [yinggaozhen/yaf-php#1]
![image](https://user-images.githubusercontent.com/37643710/61262026-585eb900-a7b6-11e9-94ea-c65c1260527d.png)
phpstrom设置的路径有调整
版本183.5912.26
按照文案一直找不到    `Setting` -> `PHP`   在哪儿。。

**Comment by yinggaozhen** [comment]
@declandragon 你好，已调整

**Comment by declandragon** [comment]
> @declandragon 你好，已调整

@yinggaozhen 你好，辛苦了，应该是下面这样  ：） 
 菜单 `File` -> `Setting` -> `Languages & Frameworks` -> `PHP` -> 添加`Yaf-PHP`文件路径 -> `apply`
